// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.Collections.Generic;

namespace HelloApi.Bulk;


    public class DateOnlyConverter : ValueConverter<DateOnly, string>
    {
        public DateOnlyConverter()
            : base(d => d.ToString("yyyy-MM-dd"),
                   s => DateOnly.Parse(s))
        { }
    }

    public class NullableDateOnlyConverter : ValueConverter<DateOnly?, string?>
    {
        public NullableDateOnlyConverter()
            : base(d => d.HasValue ? d.Value.ToString("yyyy-MM-dd") : null,
                   s => string.IsNullOrEmpty(s) ? null : DateOnly.Parse(s!))
        { }
    }


public class DateOnlyToStringConverter : ValueConverter<DateOnly, string>
{
    public DateOnlyToStringConverter()
        : base(
            d => d.ToString("yyyy-MM-dd"),
            s => DateOnly.Parse(s))
    { }
}

public class NullableDateOnlyToStringConverter : ValueConverter<DateOnly?, string?>
{
    public NullableDateOnlyToStringConverter()
        : base(
            d => d.HasValue ? d.Value.ToString("yyyy-MM-dd") : null,
            s => string.IsNullOrEmpty(s) ? null : DateOnly.Parse(s))
    { }
}

// (facultatif, mais utile quand le provider ne fournit pas de comparer par défaut)
public static class DateOnlyComparers
{
    public static readonly ValueComparer<DateOnly> NonNullable =
        new ValueComparer<DateOnly>(
            (a, b) => a == b,
            d => d.GetHashCode());

    public static readonly ValueComparer<DateOnly?> Nullable =
        new ValueComparer<DateOnly?>(
            (a, b) => a.GetValueOrDefault() == b.GetValueOrDefault(),
            d => d.HasValue ? d.Value.GetHashCode() : 0);
}


