// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using HelloApi.Entities;
using Microsoft.EntityFrameworkCore;

namespace HelloApi.Contexts;

public partial class HelloApiContext : DbContext
{
    public HelloApiContext(DbContextOptions<HelloApiContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TPersonEntity> TPersons { get; set; }

    public virtual DbSet<TStockPartEntity> TStockParts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TPersonEntity>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.DateBorn)
                .HasColumnType("DATE")
                .HasConversion(
                    d => d.ToString("yyyy-MM-dd"),
                    s => DateOnly.ParseExact(s, "yyyy-MM-dd"));

            entity.Property(e => e.DateDead)
                  .HasColumnType("DATE")
                  .HasConversion(
                      d => d.HasValue ? d.Value.ToString("yyyy-MM-dd") : null,
                      s => string.IsNullOrEmpty(s) ? null : DateOnly.ParseExact(s!, "yyyy-MM-dd"));
        });

        modelBuilder.Entity<TStockPartEntity>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UnitPrice).HasDefaultValueSql("0.0");
        });

        OnModelCreatingPartial(modelBuilder);
    }




    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);



}