// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelloApi.Entities;

public partial class TPersonEntity
{
    [Key]
    public int Id { get; set; }

    public string Nom { get; set; } = null!;

    public string Prenom { get; set; } = null!;

    [Column(TypeName = "DATE")]
    public DateOnly DateBorn { get; set; }

    [Column(TypeName = "DATE")]
    public DateOnly? DateDead { get; set; }

    public string? Nationalite { get; set; }
}