// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelloApi.Entities;

[Index("PartCode", IsUnique = true)]
public partial class TStockPartEntity
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "VARCHAR(50)")]
    public string PartCode { get; set; } = null!;

    [Column(TypeName = "VARCHAR(150)")]
    public string PartName { get; set; } = null!;

    public string? Description { get; set; }

    public int CurrentStock { get; set; }

    public int MinimalStock { get; set; }

    [Column(TypeName = "DECIMAL(10, 2)")]
    public int UnitPrice { get; set; }

    [Column(TypeName = "VARCHAR(100)")]
    public string? Location { get; set; }

    [Column(TypeName = "VARCHAR(100)")]
    public string? Supplier { get; set; }

    [Column(TypeName = "DATETIME")]
    public DateOnly? LastEntryDate { get; set; }

    [Column(TypeName = "DATETIME")]
    public DateTime? LastExitDate { get; set; }

    [Column(TypeName = "BOOLEAN")]
    public bool IsActive { get; set; }

    [Column(TypeName = "DATETIME")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "DATETIME")]
    public DateTime? UpdatedAt { get; set; }

    [Column(TypeName = "TEXT(20)")]
    public string? CreateBy { get; set; }

    [Column(TypeName = "TEXT(20)")]
    public string? UpdateBy { get; set; }
}